<?php
/**
 * Locale data for 'pa_IN'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2011 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '4123',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##,##0%',
  'currencyFormat' => '¤ #,##,##0.00',
  'currencySymbols' => 
  array (
    'AFN' => 'Af',
    'ANG' => 'NAf.',
    'AOA' => 'Kz',
    'ARA' => '₳',
    'ARL' => '$L',
    'ARM' => 'm$n',
    'ARS' => 'AR$',
    'AUD' => 'AU$',
    'AWG' => 'Afl.',
    'AZN' => 'man.',
    'BAM' => 'KM',
    'BBD' => 'Bds$',
    'BDT' => 'Tk',
    'BEF' => 'BF',
    'BHD' => 'BD',
    'BIF' => 'FBu',
    'BMD' => 'BD$',
    'BND' => 'BN$',
    'BOB' => 'Bs',
    'BOP' => '$b.',
    'BRL' => 'R$',
    'BSD' => 'BS$',
    'BTN' => 'Nu.',
    'BWP' => 'BWP',
    'BZD' => 'BZ$',
    'CAD' => 'CA$',
    'CDF' 6 => 'ਸ਼ਨੀ.',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => 'ਐ',
      1 => 'ਸੋ',
      2 => 'ਮੰ',
      3 => 'ਬੁੱ',
      4 => 'ਵੀ',
      5 => 'ਸ਼ੁੱ',
      6 => 'ਸ਼',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'ਈਸਾਪੂਰਵ',
      1 => 'ਸੰਨ',
    ),
    'wide' => 
    array (
      0 => 'ਈਸਾਪੂਰਵ',
      1 => 'ਸੰਨ',
    ),
    'narrow' => 
    array (
      0 => 'ਈਸਾਪੂਰਵ',
      1 => 'ਸੰਨ',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, dd MMMM y',
    'long' => 'd MMMM y',
    'medium' => 'd MMM y',
    'short' => 'dd/MM/yyyy',
  ),
  'timeFormats' => 
  array (
    'full' => 'h:mm:ss a zzzz',
    'long' => 'h:mm:ss a z',
    'medium' => 'h:mm:ss a',
    'short' => 'h:mm a',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'ਸਵੇਰੇ',
  'pmName' => 'ਸ਼ਾਮ',
  'orientation' => 'ltr',
  'pluralRules' => 
  array (
    0 => 'n==1',
    1 => 'true',
  ),
);
